### ISSUE TITLE
Dynamic Menus working with interactive messages but do not work in dialogs

### ISSUE THREAD

**Issue by onzali** [slackapi/python-message-menu-example#6] opened 2018-08-08 09:27 UTC
Any suggestions? 
This is my piece of code:

`menu_options = {
        "options": [
            {
                "text": "Cappuccino",
                "value": "cappuccino"
            },
            {
                "text": "Latte",
                "value": "latte"
            }
        ]
    }
    return Response(json.dumps(menu_options), mimetype='application/json')`

**Comment by grayontheweb** [comment] 2018-11-04 09:49
A bit of a late response, but I just dealt with the same issue. My problem was that the dialog options expect a different format than the interactive messages. See:

https://api.slack.com/dialogs#dynamic_select_elements_external

If you change `text` to `label` in your options, it should work.

**Comment by aoberoi** [comment] 2018-12-12 01:28
thanks @grayontheweb, i can confirm that this is the main difference. i'll close this issue since it seems to be resolved now.

**Closed as completed by aoberoi** 2018-12-12 01:28 UTC
Labels: question
